services:
  db:
    image: ./database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql

  backend:
    image: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    image: ./fontend
    depends_on:
      - backend
    restart: always
    ports:
      - "3000:3000"

volumes:
  db-data:
