services:
  db:
    build:
      context: ./database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql

  backend:
    build:
      context: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "3000:3000"

volumes:
  db-data:
