services:
  db:
    image: postgres-db:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql

  backend:
    image: backend-library:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    image: my-react-app:latest
    depends_on:
      - backend
    restart: always
    ports:
      - "3000:3000"

volumes:
  db-data:
