CREATE TABLE Book
(
    isbn               INT PRIMARY KEY UNIQUE,
    title              VARCHAR(100)  NOT NULL,
    year_of_publishing INT           NOT NULL,
    number_of_pages    INT           NOT NULL,
    annotation         VARCHAR(1000) NOT NULL,
    book_photo         varchar(100)  NOT NULL,
    language           VARCHAR(50)   NOT NULL
);

CREATE TABLE Author
(
    id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name     VARCHAR(100) NOT NULL,
    date_of_birth DATE         NOT NULL,
    nationality   VARCHAR(50)  NOT NULL
);

-- Join Table
CREATE TABLE Author_of_the_book
(
    author_id INT REFERENCES Author (id),
    book_isbn INT REFERENCES Book (isbn),
    PRIMARY KEY (author_id, book_isbn)
);

CREATE TABLE Translator
(
    id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(100) NOT NULL
);

-- Join Table
CREATE TABLE Translator_of_the_book
(
    translator_id INT REFERENCES Translator (id),
    book_isbn     INT REFERENCES Book (isbn),
    PRIMARY KEY (translator_id, book_isbn)
);

CREATE TABLE Genre
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    genre_name VARCHAR(50) NOT NULL
);

-- Join Table
CREATE TABLE Genre_of_the_book
(
    genre_id  INT REFERENCES Genre (id),
    book_isbn INT REFERENCES Book (isbn),
    PRIMARY KEY (genre_id, book_isbn)
);

CREATE TABLE Reader
(
    id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name     VARCHAR(100) NOT NULL,
    birth_date    DATE         NOT NULL,
    password      VARCHAR(100) NOT NULL,
    phone_number  VARCHAR(50)  NOT NULL,
    email         VARCHAR(50)  NOT NULL,
    profile_photo VARCHAR(300),
    debtor        BOOLEAN
);

CREATE TABLE Book_copies
(
    isbn      INT NOT NULL,
    copy_id   INT GENERATED BY DEFAULT AS IDENTITY,
    reader_id INT,
    PRIMARY KEY (isbn, copy_id),
    FOREIGN KEY (reader_id) REFERENCES Reader (id)
);

CREATE TABLE Librarian
(
    id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name     VARCHAR(100) NOT NULL,
    password      VARCHAR(100) NOT NULL,
    phone_number  VARCHAR(50)  NOT NULL,
    email         VARCHAR(50)  NOT NULL,
    profile_photo VARCHAR(300) NOT NULL
);

CREATE TABLE Operations_with_books
(
    id               INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_of_issuance DATE,
    return_deadline  DATE,
    date_of_return   DATE,
    librarian_id     INT NOT NULL,
    reader_id        INT NOT NULL,
    book_isbn        INT NOT NULL,
    FOREIGN KEY (librarian_id) REFERENCES Librarian (id),
    FOREIGN KEY (reader_id) REFERENCES Reader (id),
    FOREIGN KEY (book_isbn) REFERENCES Book (isbn)
);

CREATE TABLE Book_reservation
(
    id                  INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_of_reservation TIMESTAMP,
    reader_id           INT,
    book_isbn           INT,
    FOREIGN KEY (reader_id) REFERENCES Reader (id),
    FOREIGN KEY (book_isbn) REFERENCES Book (isbn)
);

